### src/config/config.yaml
defaults:
  - parameters: paramMLPClassifier

local: C:\Users\abfernan\CrossCanFloodMapping\FloodProbabRNCanAbd\datasets
pathTrainingDataset: AL_Lethbridge_FullBasin_Cilp_FullDataset_Class1.csv
pathTestDataset: MLPBinary_basin5_Test.csv
clasOfInterest: Metric  # write 'Metric' if binary or class_# if multiclass
weightPenalty: 0.01
targetColName: percentage
firstInterval: 'list(np.arange(50,1001,10))' #'[280]' 
loops: 2
### src/config/parameters/paramMLPClassifier.yaml
# @package _group_
name: param