### src/config/config.yaml
defaults:
  - parameters: paramClassifier

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/datasets/
pathTrainingDataset: allVs_basin4_CleanDataSet_Training.csv
pathTestDataset: basin4_CleanDataSet_VsAll_Test.csv
weightPenalty: 0.01
targetColName: percentage

### src/config/parameters/paramClassifier.yaml
# @package _group_
name: param