### src/config/config.yaml
defaults:
  - parameters: paramOneVsAll

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/
pathTrainingDataset: basin1Train.csv
pathValidationDataset: basin1Validation.csv
weightPenalty: 0.01
targetColName: percentage

### src/config/parameters/paramClassifier.yaml
# @package _group_
name: param