### src/config/config.yaml
defaults:
  - parameters: paramClassifier

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/
pathTrainingDataset: basin1TrainUnbalanced.csv
pathTestDataset: basin1Test.csv
weightPenalty: 0.01
targetColName: percentage

### src/config/parameters/paramClassifier.yaml
# @package _group_
name: param