### src/config/config.yaml
defaults:
  - parameters: paramClassifier

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/
pathDataset: basin1_FaccNorm.csv
percentOfValidation: 0.2
weightPenalty: 0.01

### src/config/parameters/paramClassifier.yaml
# @package _group_
name: param