### src/config/config.yaml
defaults:
  - _self_
  - parameters: paramMLPClassifier

local: C:\Users\abfernan\CrossCanFloodMapping\FloodProbabRNCanAbd\datasets\
datasetFolder : C:\Users\abfernan\CrossCanFloodMapping\FloodMappingProjData\HRDTMByAOI\A_DatasetsForMLP\StratifiedSampling\
trainingDataset: class5_Full_Training.csv
validationDataset: class5_Full_Validation.csv
# weightPenalty: 0.01
targetColName: Labels

### src/config/parameters/paramMLPClassifier.yaml
# @package _group_
name: param