### src/config/config.yaml
defaults:
  - parameters: paramMLPClassifier
  - _self_
 
local: C:\Users\abfernan\CrossCanFloodMapping\FloodProbabRNCanAbd\datasets\
datasetFolder : C:\Users\abfernan\CrossCanFloodMapping\FloodMappingProjData\HRDTMByAOI\A_DatasetsForMLP\StratifiedSampling_RasterizeCombined\
trainingDataset: class1_Full_Normalized_Training.csv
validationDataset: class1_Full_Normalized_Validation.csv
# weightPenalty: 0.01
targetColName: Labels

### Configuration for Multirun. Add all parameters to combine in the <params> dictionary. Follow the sintax:
###   ++.++parameters.optimizer.lr: val_1,val_2,...,val_n
hydra:
    mode: MULTIRUN
    sweeper:
        params:
          ++parameters.model._target_: models.MLP_4 ,models.MLP_5,models.MLP_6
          ++parameters.optimizer.lr: 0.005, 0.002, 0.0012
          ++parameters.scheduler.factor: 0.80,0.9
          ++parameters.batchSize: 50,100

           