### src/config/config.yaml
defaults:
  - parameters: paramMLPClassifier

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/datasets/datasets4MLP/
pathTrainingDataset: MLP_basin1Light_Clean_Training.csv
pathTestDataset: MLP_basin1Light_Clean_Test.csv
clasOfInterest: class_5  # write 'Metric' if binary or class_# if multiclass
weightPenalty: 0.01
targetColName: percentage
firstInterval: '[280]' # 'list(np.arange(50,1001,10))'
loops: 2
### src/config/parameters/paramMLPClassifier.yaml
# @package _group_
name: param
