### src/config/config.yaml
defaults:
  - parameters: paramClassifier.yaml

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/datasets/dataset4MLP/
pathTrainingDataset: basin3_Training.csv
pathTestDataset: basin3_Test.csv
weightPenalty: 0.01
targetColName: Labels
datasetsList : C:\Users\abfernan\CrossCanFloodMapping\FloodMappingProjData\HRDTMByAOI\FullDatasetsList.csv

### src/config/parameters/paramClassifier.yaml
# @package _group_
name: param