### src/config/config.yaml
defaults:
  - parameters: paramMLPClassifier

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/datasets/datasets4MLP_Binary/
pathTrainingDataset: MLPBinary_basin5_Training.csv
pathTestDataset: MLPBinary_basin5_Test.csv
clasOfInterest: Metric  # write 'Metric' if binary or class_# if multiclass
weightPenalty: 0.01
targetColName: percentage
firstInterval: 'list(np.arange(50,1001,10))' #'[280]' 
loops: 2
### src/config/parameters/paramMLPClassifier.yaml
# @package _group_
name: param