### config/parameters/param.yaml    list(np.linspace(2, 40, 10).astype(int))
n_estimators: '[150]' #'np.linspace(90, 150, 5).astype(int)'
max_depth: '[None]'
max_features: '[0.8]'
max_leaf_nodes: '[None]'
bootstrap: '[True,False]'
