### config/parameters/param.yaml    list(np.linspace(2, 40, 10).astype(int))
estimator__n_estimators: '[58]' 
estimator__max_depth: '[None]'
estimator__max_features: '[0.8]'
estimator__max_leaf_nodes: '[None]'
n_jobs:  '[-1]'
verbose: '[5]'