### config/parameters/param.yaml    list(np.linspace(2, 40, 10).astype(int))
n_estimators: '[100]'  # 'np.linspace(50,150,10).astype(int)'
max_depth: '[None]'
max_features: '[1]'
max_leaf_nodes: '[None]'
bootstrap: '[False]'
