### config/parameters/param.yaml  
epochs : 100
lr : 0.01
testSize : 0.2
batchSize : 64
random_state: 50
hidden_layer_sizes: []
early_stopping: True
verbose: False
tol: 0.00010
validation_fraction: 0.1
warm_start: False
